Repository wecode-bootcamp-korea/21-1st-seolleungbeer-frontend, pull requests merged in 2021-06, with the labels that each got.

#3 Fix: Login페이지 수정요청사항 수정
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Routes.js
  src/Style/common.scss
  src/utils/validator.js
Labels: Status: Accepted

#4 [21기 김건우] Add : 메인페이지 레이아웃 구현
  public/Data/main.json
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/UserLink.js
  src/Components/Nav/UserLink.scss
  src/Pages/Main/Carousel.js
  src/Pages/Main/Carousel.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#5 [21기 김건우] Modify : 주소에 따른 className 추가
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/UserLink.js
  src/Components/Nav/UserLink.scss
  src/Pages/Main/Carousel.js
  src/Pages/Main/Carousel.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
Labels: Status: Accepted

#6 [21기 백진수] SignUp 페이지 기능구현(conflict 해결)
  public/images/profile.jpeg
  public/index.html
  src/Pages/Login/Login.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Routes.js
  src/config.js
  src/utils/validator.js
Labels: Status: 리뷰 요청

#7 [21기 김건우] Nav 태그 수정 및 css 수정
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/UserLink.js
  src/Components/Nav/UserLink.scss
Labels: Status: Accepted

#9 [21기 김건우] 상품 상세 페이지 구현
  package-lock.json
  package.json
  public/Data/detail.json
  public/Data/detail.template
  public/index.html
  src/Components/Goods/DeliveryInfo.js
  src/Components/Goods/Goods.scss
  src/Components/Goods/GoodsInfo.js
  src/Components/Goods/Refunds.js
  src/Components/Nav/UserLink.js
  src/Components/ShoppingModal/Popup.js
  src/Components/ShoppingModal/Popup.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailSections/Categories.js
  src/Pages/Detail/DetailSections/CategoriesSections/CategoriesSections.scss
  src/Pages/Detail/DetailSections/CategoriesSections/GoodsDetail.js
  src/Pages/Detail/DetailSections/CategoriesSections/GoodsReview.js
  src/Pages/Detail/DetailSections/DetailSection.scss
  src/Pages/Detail/DetailSections/Goods.js
  src/Pages/Detail/DetailSections/GoodsSections/BuyButtonGroup.js
  src/Pages/Detail/DetailSections/GoodsSections/GoodsAmount.js
  src/Pages/Detail/DetailSections/GoodsSections/GoodsName.js
  src/Pages/Detail/DetailSections/GoodsSections/GoodsSections.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#8 [21기 백진수] Shop 페이지 수정요청 사항 수정
  public/Data/items.json
  public/images/defaultImage.jpg
  src/Pages/Login/Login.js
  src/Pages/Shop/Category/Category.js
  src/Pages/Shop/Category/Category.scss
  src/Pages/Shop/Category/Input/Input.js
  src/Pages/Shop/Category/Input/Input.scss
  src/Pages/Shop/EmptyList/EmptyList.js
  src/Pages/Shop/EmptyList/EmptyList.scss
  src/Pages/Shop/Item/Item.js
  src/Pages/Shop/Item/Item.scss
  src/Pages/Shop/ItemList/ItemList.js
  src/Pages/Shop/ItemList/ItemList.scss
  src/Pages/Shop/LoadingList/LoadingList.js
  src/Pages/Shop/LoadingList/LoadingList.scss
  src/Pages/Shop/Shop.js
  src/Pages/Shop/Shop.scss
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/config.js
  src/utils/priceFormat.js
Labels: Status: Accepted

#10 [21기 백진수] SignUp 페이지 모바일 중복체크 버튼 추가- 리뷰요청사항 수정
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
Labels: Status: Accepted

#11 [21기 김건우] Modify : 상품 상세 페이지
  src/Pages/Detail/Detail.js
Labels: Status: 리뷰 요청

#15 [21기 백진수] git conflict 해결
  src/config.js
Labels: Status: 리뷰 요청

#13 [21기 백진수] 리뷰요청 사항 수정
  package-lock.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/utils/setToken.js
Labels: Status: 리뷰 요청

#12 [21기 김건우] 결제 페이지 구현
  package-lock.json
  package.json
  src/Components/Payment/Card.js
  src/Components/Payment/Card.scss
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#14 [21기 백진수] 장바구니 페이지 기능구현
  public/Data/basket.json
  public/images/cat.jpg
  src/Pages/Basket/Basket.js
  src/Pages/Basket/Basket.scss
  src/Pages/Basket/Item/Item.js
  src/Pages/Basket/Item/Item.scss
  src/Pages/Basket/ItemList/ItemList.js
  src/Pages/Basket/ItemList/ItemList.scss
  src/Pages/Basket/QuantityForm/QuantityForm.js
  src/Pages/Basket/QuantityForm/QuantityForm.scss
  src/Pages/SignUp/SignUp.js
  src/Routes.js
  src/config.js
  src/defaultImage.js
  src/utils/sum.js
  src/utils/token.js
Labels: Status: 수정 요청

#16 [21기 백진수] 장바구니 페이지 리팩토링
  package-lock.json
  src/Pages/Basket/Basket.js
  src/Pages/Login/Login.js
  src/utils/setToken.js
Labels: Status: 리뷰 요청

#17 [21기 백진수] 로그인 애니메이션
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/LoginAnimation/Beer.js
  src/Pages/Login/LoginAnimation/BeerFoam.js
  src/Pages/Login/LoginAnimation/Bubble.js
  src/Pages/Login/LoginAnimation/LoginAnimation.js
  src/Pages/Login/LoginAnimation/LoginAnimation.scss
  src/Pages/Login/LoginAnimation/MovingPoint.js
Labels: Status: 리뷰 요청

#18 [21기 백진수] api 주소 수정
  src/Pages/Basket/Basket.js
  src/Pages/Detail/Detail.js
  src/Pages/Login/Login.js
  src/Pages/Payment/Payment.js
  src/Pages/Shop/Shop.js
  src/Pages/SignUp/SignUp.js
  src/config.js
Labels: Status: 리뷰 요청

#19 [21기 김건우] 결제하기 수정
  src/Pages/Detail/Detail.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/PaymentSections/CustomerInfo.js
  src/Pages/Payment/PaymentSections/DeliveryInfo.js
  src/Pages/Payment/PaymentSections/FinalPaymentAmount.js
  src/Pages/Payment/PaymentSections/OrderInfo.js
  src/Pages/Payment/PaymentSections/Paygo.js
  src/Pages/Payment/PaymentSections/PaymentInfo.js
  src/utils/payment.js
Labels: Status: 리뷰 요청

#22 [21기 김건우] 결제 API conflict 해결
  src/Pages/Payment/Payment.js
  src/Pages/Payment/PaymentSections/OrderInfo.js
Labels: Status: 리뷰 요청

#24 [21기 김건우] Fix : Nav 수정
  src/Components/Nav/UserLink.js
Labels: Status: 리뷰 요청

#26 [21기 백진수] footer 완료
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Payment/Payment.js
  src/Routes.js
Labels: Status: 리뷰 요청

#28 [21기 백진수] css 최종 수정
  public/index.html
  src/Components/Payment/Card.scss
  src/Components/ShoppingModal/Popup.js
  src/Components/ShoppingModal/Popup.scss
  src/Pages/Basket/Basket.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/LoginAnimation/LoginAnimation.js
  src/Pages/Login/LoginAnimation/LoginAnimation.scss
  src/Pages/Main/Carousel.scss
  src/Pages/Shop/ItemList/ItemList.scss
  src/Pages/SignUp/SignUp.scss
  src/Style/reset.scss
Labels: Status: 리뷰 요청

#29 [21기 백진수] 결제창 넘어가기 수정
  src/Pages/Basket/Basket.js
Labels: Status: 리뷰 요청
